### PR TITLE
Phase 4+5, PVP updates and ZA Timed Chest fix

### PR DESCRIPTION
**Pull request by NNCSavage**
PVP items should be updated with current season values for honor and marks.
Collections now has a separate Phase 4 and Phase 5 list, including epics gems for badges in Phase 5.
ZA Timed Chest 2 and 3 were incorrect and were changed.

### CODE REVIEW

**Comment by mykkenny** [comment]
Missing the P4 BoJ necks

**Comment by NNCSavage** [comment]
The only Phase 4 BoJ neck I can locate is the Brooch of Deftness. I also checked G'eras in game and saw no other necks. What others are missing?

**Comment by mykkenny** [comment]
https://tbc.wowhead.com/item=33296/brooch-of-deftness

This is up for sure, there are definitely others. Maybe you added the item, but the category isn't available to choose from?

**Comment by NNCSavage** [comment]
Thanks - should be fixed now. Let me know if you see anything else.

**Comment by mykkenny** [comment]
@Hoizame Any chance you could accept this merge request? Maybe even let one of these people trying to get the addon updated be a contributor who can update and push those updates? A lot of people still use this addon :)

**Comment by NNCSavage** [comment]
I found two sets of item numbers for Battlemaster Trinkets - so they should now be found in both the PVP section and the badge vendor P4 > Trinket section as well as correctly priced. There was also one Vindicator's neck that was missing a price so I fixed that with the latest batch of changes.

**Comment by Hoizame** [comment]
I take a look into this today, sorry for the wait time and thanks for the work :)

**Pull request merged**
