### PR TITLE
Season of Discovery - Full Update - Last change Jan 2, 2023

### PR DESCRIPTION
**Pull request by Aleks1015**
Forked updates from Corazu!! and made some updates based on feedback in his comments in his request.

-Updated BFD Loot tables (many updates for set pieces, quest items)
-Mapped quest item rewards from BFD
-Updated NPC IDs for all BFD bosses
-Updated BFD boss levels
-Update BFD set piece mapping
-Added Ashenvale mounts
-Added New profession items
-Updated to indicate support for 1.15.0  (Fixed by Salkz)
-Updated PVP items (Added by Inariaa)

12/12/2023
Pulled data from AtlasLootClassic_SoD v0.8 By [Kwonko] on CurseForge
-Adds trash items to new BFD 10 man Raid items
-Adds item sources to tooltips for BFD 10 man Raid items
-Adds new SoD faction items
-Better Segregates SoD items from other items

12/14/2023
-Updated location of runes from honored to friendly for Alliance and Horde (Azeroth Commerce Authority & Durotar Supply and Logistics)

1/2/2024
-Added 2 new tailoring items (Invoker's Coord and Mantle).

image

image

### CODE REVIEW

**Comment by Corazu** [comment]
Thanks for making the updates, have had a busy weekend and haven't been able to make the changes yet. I closed my PR in lieu of this one since it's more up to date.

**Comment by illutian** [comment]
Just and FYI:
2x AtlasLootClassic_DungeonsAndRaids/AtlasLootClassic_DungeonsAndRaids_Vanilla.toc:3 Couldn't open AtlasLootClassic_DungeonsAndRaids/@project-version@

and

2x AtlasLootClassic_Data/AtlasLootClassic_Data_Vanilla.toc:3 Couldn't open AtlasLootClassic_Data/@project-version@

Just a small 'whoops', "## Version: " was left out so it just says "@project-version@". The other TOC files all say "## Version: @project-version@" and do not cause an error.

I made the change on mine and the errors are gone.

**Comment by arog85** [comment]
> Just and FYI: 2x AtlasLootClassic_DungeonsAndRaids/AtlasLootClassic_DungeonsAndRaids_Vanilla.toc:3 Couldn't open AtlasLootClassic_DungeonsAndRaids/@ project-version @
> 
> and
> 
> 2x AtlasLootClassic_Data/AtlasLootClassic_Data_Vanilla.toc:3 Couldn't open AtlasLootClassic_Data/@ project-version @
> 
> and..
> 
> 2x AtlasLootClassic_Crafting/AtlasLootClassic_Crafting_Vanilla.toc:3 Couldn't open AtlasLootClassic_Crafting/@ project-version @
> 
> 2x AtlasLootClassic_Factions/AtlasLootClassic_Factions_Vanilla.toc:3 Couldn't open AtlasLootClassic_Factions/@ project-version @
> 
> 2x AtlasLootClassic_PvP/AtlasLootClassic_PvP_Vanilla.toc:3 Couldn't open AtlasLootClassic_PvP/@ project-version @
> 
> Just a small 'whoops', "## Version: " was left out so it just says "@ project-version @". The other TOC files all say "## Version: @ project-version @" and do not cause an error.
> 
> Note: Spaces added because Github thinks 'at symbols' are the start of usernames... -_-'
> 
> I made the change on mine and the errors are gone.
> 
> EDIT: Should note that the TOC of each module that had the above issue were affected.

Fixed this, it was caused by having one of my works not properly updated to a version to not trigger the development version message.

**Comment by arog85** [comment]
Note there is a branch in my fork tagged as 3.2.1 to prevent development version messages.  This is to keep this pull request in-tact and the project owner here can apply the version as they see fit.

https://github.com/arog85/AtlasLootClassic/tree/sod-3.2.1

**Comment by SouD** [comment]
@Hoizame @arog85 Is there any update here that we the public are not privy to? At this rate this'd be merged when P2 is already live. 😅

**Comment by Rerox-WoW** [comment]
How do I download this version? Sorry, not a developer and no idea how guthub works.

**Comment by anon1231823** [comment]
> @Hoizame @arog85 Is there any update here that we the public are not privy to? At this rate this'd be merged when P2 is already live. 😅

I don't think @Hoizame is maintaining this addon anymore. He has been missing for months. I think he should pass the reigns over to someone else who can continue developing this addon.

**Comment by arog85** [comment]
> How do I download this version? Sorry, not a developer and no idea how github works.

If you go to my fork and use SoD 3.2.1 (supresses development version message)

Click code -> download zip -> open zip and copy only these folders in to the addons folder.



https://github.com/arog85/AtlasLootClassic/tree/sod-3.2.1

image

**Comment by arog85** [comment]
> > @Hoizame @arog85 Is there any update here that we the public are not privy to? At this rate this'd be merged when P2 is already live. 😅
> 
> I don't think @Hoizame is maintaining this addon anymore. He has been missing for months. I think he should pass the reigns over to someone else who can continue developing this addon.

Yeah I'm not too sure.  I am going to continue to update it in my fork and will start creating an update for Phase 2.  Items have been datamined, obviously drop tables aren't known.  I may look at getting it into curse forge as an SoD variant or something if @Hoizame is still inactive.

**Comment by arog85** [comment]
> @Hoizame @arog85 Is there any update here that we the public are not privy to? At this rate this'd be merged when P2 is already live. 😅

I can only direct you to my branch where I have this tagged as 3.2.1.  I will be updating for Phase 2 and I am now seriously considering adding my fork to curse forge.  I was hesitant because this is @Hoizame 's addon and I truly only wanted to help get SoD reflected in it and @Corazu 's work was extremely helpful.

**Comment by Corazu** [comment]
> > @Hoizame @arog85 Is there any update here that we the public are not privy to? At this rate this'd be merged when P2 is already live. 😅
> 
> I can only direct you to my branch where I have this tagged as 3.2.1. I will be updating for Phase 2 and I am now seriously considering adding my fork to curse forge. I was hesitant because this is @Hoizame 's addon and I truly only wanted to help get SoD reflected in it and @Corazu 's work was extremely helpful.

I'm happy to contribute towards phase 2 as well. I was hoping this would have gotten merged but it appears the author is completely mia. There is also other forks already on Curse, not sure how they stack up

**Comment by snowflame0** [comment]
This looks like it has become its own separate project, not sure how we could pull these changes in without interfering with regular classic, would probably need to rewrite a bunch of ToC files and add a bunch of checks for SoD only items. Probably better to leave it as separate for now.

**Comment by Aleks1015** [comment]
> This looks like it has become its own separate project, not sure how we could pull these changes in without interfering with regular classic, would probably need to rewrite a bunch of ToC files and add a bunch of checks for SoD only items. Probably better to leave it as separate for now.

Agreed however since 3 different games (era/hardcore albeit are the same) and the seasonal.  I separated all the changes and used the C_Seasons.GetActiveSeason() and C_Seasons.HasActiveSeason() functions in the Blizzard API to determine if on a seasonal realm.  It is outputting 2 for hardcore and 3 for season of discovery.

As a result I was able to separate it completely and have it here right now.  I used the most current branch of this version.

If you are on a hardcore or era realm, you will not see any seasonal changes at all.  On seasonal realms should all of the current updates available from SoD fork mostly.  I took some time to make sure it cleanly was separated.

It will be compatible to merge here if you agree - I can setup a compatible pull request.  Cata comfortably can be isolated because it has its own client.  

https://github.com/arog85/AtlasLootClassic_Era/tree/3.4.0-alpha

@snowflame0

**Pull request closed without merging**
